upload:
	psql -h wander -U rhh32 -d rhh32_cs461 -f PhotographyExample

download:
	pg_dump -h wander -U rhh32 -d rhh32_cs461 -f "photography_psql_database_script"

lab1:
	psql -h wander -U rhh32 -d rhh32_cs461 -f Lab1

lab1a:
	psql -h wander -U rhh32 -d rhh32_cs461 -f Lab1a